app:
  port: 3000
  env: "development"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

http:
  timeout: '10s'

context:
  timeout: '10s'

prefetch:
  urls:
    countries:
      url: "https://restcountries.com/v3.1/all?fields=name,cca3,currencies,languages,latlng,timezones"
      ttl: "168h"
    currencies:
      url: "http://data.fixer.io/api/latest?access_key=FIXER_API_KEY"
      ttl: "24h"
