services:
    redis:
        image: redis
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        entrypoint: redis-server --appendonly yes

volumes:
    redis_data:
        name: redis_data

networks:
    default:
        name: redis_network
