### GET request to the root path
GET http://localhost:3000/

### GET request for all countries
GET https://api.countrylayer.com/v2/all?access_key=52f5c8e4bf6c75ec556dbc0e25f75693

### GET request for a specific region
GET https://api.countrylayer.com/v2/region/Europe?access_key=52f5c8e4bf6c75ec556dbc0e25f75693

### GET request for a specific country
GET https://api.countrylayer.com/v2/name/Canada?access_key=52f5c8e4bf6c75ec556dbc0e25f75693&fullText=true
